layout = "row"
flow = "stack"

[[item]]
icon = "/assets/icon-deepseek.svg"
title = "DeepSeek"
subtitle = "AI Researcher"
badge = "2025-present"

[[item]]
icon = "/assets/icon-openai.png"
title = "OpenAI"
subtitle = "Machine Learning Engineer"
badge = "2021-2025"

[[item]]
icon = "/assets/icon-google.webp"
title = "Google"
subtitle = "Backend Engineer"
badge = "2018-2022"
