layout = "row"
flow = "stack"

[[item]]
title = "Tokio"
link = "https://example.com"
subtitle = "An asynchronous runtime for the Rust programming language"
badge = "2025"

[[item]]
title = "Kubernetes"
link = "https://example.com"
subtitle = "Production-Grade Container Scheduling and Management"
badge = "2024"

[[item]]
title = "Next.js"
link = "https://example.com"
subtitle = "React framework for building full-stack web applications"
badge = "2022"

[[item]]
title = "Deno"
link = "https://example.com"
subtitle = "A modern runtime for JavaScript and TypeScript"
badge = "2022"

[[item]]
title = "Grafana"
link = "https://example.com"
subtitle = "The open and composable observability and data visualization platform"
badge = "2020"

[[item]]
title = "Zustand"
link = "https://example.com"
subtitle = "Bear necessities for state management in React"
badge = "2021"
