layout = "row"
flow = "inline"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=anaconda"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=androidstudio"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=arch"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=astro"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bash"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bevy"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bun"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=cpp"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=dart"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=debian"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=deno"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=docker"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=elysia"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=flutter"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=git"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=github"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=go"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=grafana"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=haskell"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=ai"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=js"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=kubernetes"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=linux"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=neovim"
[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=nix"
[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=pinia"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=react"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=rust"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=svelte"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=typescript"


[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=wasm"

[[item]]
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=zig"
