layout = "row"
flow = "inline"

[[item]]
title = "Follow"
link = "https://example.com"
icon = "/assets/icon-follow.svg"

[[item]]
title = "VSCode"
link = "https://example.com"
icon = "/assets/icon-vsc.png"

[[item]]
title = "IntelliJ IDEA"
link = "https://example.com"
icon = "/assets/icon-idea.svg"

[[item]]
title = "Zed"
link = "https://example.com"
icon = "/assets/icon-zed.svg"
